export { HelpScoutDocsClient } from "./client.js"
export type {
  HelpScoutDocsConfig,
  DocsItem,
  DocsListResponse,
  Site,
  Collection,
  Category,
  Article,
  Visibility,
  ArticleStatus,
  ArticleListStatus,
  SortOrder,
  ArticleSort,
  CategoryDefaultSort,
  CreateCollectionInput,
  UpdateCollectionInput,
  CreateCategoryInput,
  UpdateCategoryInput,
  ListArticlesInput,
  SearchArticlesInput,
  CreateArticleInput,
  UpdateArticleInput,
} from "./types.js"
